data:extend(
{
--RAWS
{
    type = "fluid",
    name = "gas-natural-1",
    icon = "__angelspetrochem__/graphics/icons/gas-natural-1.png",
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 0.50, g = 0.70, b = 0.40},
    flow_color = {r = 0.50, g = 0.70, b = 0.40},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
-- {
    -- type = "fluid",
    -- name = "gas-natural-2",
    -- icon = "__angelspetrochem__/graphics/icons/gas-natural-2.png",
	-- default_temperature = 25,
    -- heat_capacity = "1KJ",
    -- base_color = {r = 0.50, g = 0.70, b = 0.40},
    -- flow_color = {r = 0.50, g = 0.70, b = 0.40},
    -- max_temperature = 100,
	-- pressure_to_speed_ratio = 0.4,
    -- flow_to_energy_ratio = 0.59,
-- },
{
    type = "fluid",
    name = "liquid-multi-phase-oil",
    icon = "__angelspetrochem__/graphics/icons/liquid-multi-phase-oil.png",
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-raw-1",
    icon = "__angelspetrochem__/graphics/icons/gas-raw-1.png",
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 0.70, g = 0.90, b = 0.60},
    flow_color = {r = 0.70, g = 0.90, b = 0.60},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
-- {
    -- type = "fluid",
    -- name = "gas-raw-2",
    -- icon = "__angelspetrochem__/graphics/icons/gas-raw-1.png",
	-- default_temperature = 25,
    -- heat_capacity = "1KJ",
    -- base_color = {r = 0.70, g = 0.90, b = 0.60},
    -- flow_color = {r = 0.70, g = 0.90, b = 0.60},
    -- max_temperature = 100,
	-- pressure_to_speed_ratio = 0.4,
    -- flow_to_energy_ratio = 0.59,
-- },
{
    type = "fluid",
    name = "liquid-condensates",
    icon = "__angelspetrochem__/graphics/icons/liquid-condensates.png",
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-acid",
    icon = "__angelspetrochem__/graphics/icons/gas-acid.png",
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "liquid-ngl",
    icon = "__angelspetrochem__/graphics/icons/liquid-ngl.png",
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-residual",
    icon = "__angelspetrochem__/graphics/icons/gas-residual.png",
	default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
}
)