data:extend(
{
--RAWS
{
    type = "fluid",
    name = "gas-natural-1",
    icon = "__angelspetrochem__/graphics/icons/gas-natural-1.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.50, g = 0.70, b = 0.40},
    flow_color = {r = 0.50, g = 0.70, b = 0.40},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-natural-2",
    icon = "__angelspetrochem__/graphics/icons/gas-natural-2.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.50, g = 0.70, b = 0.40},
    flow_color = {r = 0.50, g = 0.70, b = 0.40},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "liquid-multi-phase-oil",
    icon = "__angelspetrochem__/graphics/icons/liquid-multi-phase-oil.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-raw-1",
    icon = "__angelspetrochem__/graphics/icons/gas-raw-1.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.70, g = 0.90, b = 0.60},
    flow_color = {r = 0.70, g = 0.90, b = 0.60},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-raw-2",
    icon = "__angelspetrochem__/graphics/icons/gas-raw-1.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.70, g = 0.90, b = 0.60},
    flow_color = {r = 0.70, g = 0.90, b = 0.60},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "liquid-condensates",
    icon = "__angelspetrochem__/graphics/icons/liquid-condensates.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-acid",
    icon = "__angelspetrochem__/graphics/icons/gas-acid.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "liquid-ngl",
    icon = "__angelspetrochem__/graphics/icons/liquid-ngl.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
--CARBON BASIC
	--GAS
{
    type = "fluid",
    name = "gas-methane",
    icon = "__angelspetrochem__/graphics/icons/gas-methane.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-ethane",
    icon = "__angelspetrochem__/graphics/icons/gas-ethane.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-butane",
    icon = "__angelspetrochem__/graphics/icons/gas-butane.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
	--OIL
{
    type = "fluid",
    name = "liquid-naphtha",
    icon = "__angelspetrochem__/graphics/icons/liquid-naphtha.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "liquid-mineral-oil",
    icon = "__angelspetrochem__/graphics/icons/liquid-mineral-oil.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "liquid-fuel-oil",
    icon = "__angelspetrochem__/graphics/icons/liquid-fuel-oil.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
	--CRACKING
{
    type = "fluid",
    name = "gas-methanol",
    icon = "__angelspetrochem__/graphics/icons/gas-methanol.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-ethylene",
    icon = "__angelspetrochem__/graphics/icons/gas-ethylene.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-benzene",
    icon = "__angelspetrochem__/graphics/icons/gas-benzene.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-synthesis",
    icon = "__angelspetrochem__/graphics/icons/gas-synthesis.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
	--CHEMICAL PROCESSING
{
    type = "fluid",
    name = "gas-butadiene",
    icon = "__angelspetrochem__/graphics/icons/gas-butadiene.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-phenol",
    icon = "__angelspetrochem__/graphics/icons/gas-phenol.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-ethylbenzene",
    icon = "__angelspetrochem__/graphics/icons/gas-ethylbenzene.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-styrene",
    icon = "__angelspetrochem__/graphics/icons/gas-styrene.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-formaldehyde",
    icon = "__angelspetrochem__/graphics/icons/gas-formaldehyde.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-polyethylene",
    icon = "__angelspetrochem__/graphics/icons/gas-polyethylene.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-chlor-methane",
    icon = "__angelspetrochem__/graphics/icons/gas-chlor-methane.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
--CHEMICAL BASIC
{
    type = "fluid",
    name = "gas-hydrogen",
    icon = "__angelspetrochem__/graphics/icons/gas-hydrogen.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-oxygen",
    icon = "__angelspetrochem__/graphics/icons/gas-oxygen.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-chlorine",
    icon = "__angelspetrochem__/graphics/icons/gas-chlorine.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-hydrogen-chloride",
    icon = "__angelspetrochem__/graphics/icons/gas-hydrogen-chloride.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-carbon-monoxide",
    icon = "__angelspetrochem__/graphics/icons/gas-carbon-monoxide.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-carbon-dioxide",
    icon = "__angelspetrochem__/graphics/icons/gas-carbon-dioxide.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "liquid-hydrofluoric-acid",
    icon = "__angelspetrochem__/graphics/icons/liquid-hydrofluoric-acid.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "item",
    name = "solid-sodium-hydroxide",
    icon = "__angelspetrochem__/graphics/icons/solid-sodium-hydroxide.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[solid-sodium-hydroxide]",
    stack_size = 200
},
--NITROGEN
{
    type = "fluid",
    name = "gas-nitrogen",
    icon = "__angelspetrochem__/graphics/icons/gas-nitrogen.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-ammonia",
    icon = "__angelspetrochem__/graphics/icons/gas-ammonia.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-ammonium-chloride",
    icon = "__angelspetrochem__/graphics/icons/gas-ammonium-chloride.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-urea",
    icon = "__angelspetrochem__/graphics/icons/gas-urea.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "gas-melamine",
    icon = "__angelspetrochem__/graphics/icons/gas-melamine.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
--SULFUR
{
    type = "fluid",
    name = "gas-hydrogen-sulfide",
    icon = "__angelspetrochem__/graphics/icons/gas-hydrogen-sulfide.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "item",
    name = "solid-sulfur",
    icon = "__angelspetrochem__/graphics/icons/solid-sulfur.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[solid-sulfur]",
    stack_size = 200
},
{
    type = "fluid",
    name = "gas-sulfur-dioxide",
    icon = "__angelspetrochem__/graphics/icons/gas-sulfur-dioxide.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "liquid-sulfuric-acid",
    icon = "__angelspetrochem__/graphics/icons/liquid-sulfuric-acid.png",
	default_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r = 0.1, g = 0.1, b = 0.1},
    flow_color = {r = 0.1, g = 0.1, b = 0.1},
    max_temperature = 100,
	pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
},
{
    type = "item",
    name = "solid-calcium-sulfate",
    icon = "__angelspetrochem__/graphics/icons/solid-calcium-sulfate.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[solid-calcium-sulfate]",
    stack_size = 200
},
--BYPRODUCTS SOLIDS
{
    type = "item",
    name = "solid-carbon",
    icon = "__angelspetrochem__/graphics/icons/solid-carbon.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[carbon]",
	fuel_value = "15MJ",
    stack_size = 200
},
{
    type = "item",
    name = "solid-pet-coke",
    icon = "__angelspetrochem__/graphics/icons/pet-coke.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[pet-coke]",
	fuel_value = "30MJ",
    stack_size = 200
},
{
    type = "item",
    name = "solid-plastic-1",
    icon = "__angelspetrochem__/graphics/icons/solid-plastic-1.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[solid-plastic-2]",
    stack_size = 200
},
{
    type = "item",
    name = "solid-plastic-2",
    icon = "__angelspetrochem__/graphics/icons/solid-plastic-1.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[solid-plastic-2]",
    stack_size = 200
},
{
    type = "item",
    name = "solid-resin-1",
    icon = "__angelspetrochem__/graphics/icons/solid-resin-1.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[solid-resin-1]",
    stack_size = 200
},
{
    type = "item",
    name = "solid-resin-2",
    icon = "__angelspetrochem__/graphics/icons/solid-resin-1.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[solid-resin-2]",
    stack_size = 200
},
{
    type = "item",
    name = "solid-rubber",
    icon = "__angelspetrochem__/graphics/icons/solid-rubber.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[solid-rubber]",
    stack_size = 200
},
{
    type = "item",
    name = "fluorite-ore",
    icon = "__angelspetrochem__/graphics/icons/ore-fluorite.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[fluorite-ore]",
    stack_size = 200
},
--CATALYSTS
{
    type = "item",
    name = "catalyst-aluminium",
    icon = "__angelspetrochem__/graphics/icons/catalyst-metal.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[catalyst-aluminium]",
    stack_size = 200
},
{
    type = "item",
    name = "catalyst-cobalt",
    icon = "__angelspetrochem__/graphics/icons/catalyst-metal.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[catalyst-cobalt]",
    stack_size = 200
},
{
    type = "item",
    name = "catalyst-iron",
    icon = "__angelspetrochem__/graphics/icons/catalyst-metal.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[catalyst-iron]",
    stack_size = 200
},
{
    type = "item",
    name = "catalyst-platinum",
    icon = "__angelspetrochem__/graphics/icons/catalyst-metal.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[catalyst-platinum]",
    stack_size = 200
},
{
    type = "item",
    name = "catalyst-silver",
    icon = "__angelspetrochem__/graphics/icons/catalyst-metal.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[catalyst-silver]",
    stack_size = 200
},
{
    type = "item",
    name = "catalyst-titan",
    icon = "__angelspetrochem__/graphics/icons/catalyst-metal.png",
    flags = {"goes-to-main-inventory"},
	subgroup = "petrochem-raw",
    order = "a[catalyst-titan]",
    stack_size = 200
},
}
)